---
abstract: 'LDAP client library'
author:
  - 'Graham Barr <gbarr@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: Net::LDAP
name: perl-ldap
no_index:
  directory:
    - inc
    - t
requires:
  Convert::ASN1: 0.07
  perl: 5.004
resources:
  ListArchive: http://perl.markmail.org/search/list:perl-ldap
  MailingList: http://lists.cpan.org/showlist.cgi?name=perl-ldap
  homepage: http://ldap.perl.org/
  repository: http://git.goingon.net/?p=perl-lda.git;a=summary
version: 0.38
